language: python
matrix:
  include:
  - name: linux_py3
    python: 3.7
    os: linux
    before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install pip
    - fgrep -v pysnptools requirements.txt > r.nopysnptools.txt
    - conda install --file r.nopysnptools.txt
    - conda install cython
    - pip install -r requirements.txt

  - name: linux_py2
    python: 2.7
    os: linux
    before_install:
    #see https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
    - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install pip
    - fgrep -v pysnptools requirements.txt > r.nopysnptools.txt
    - conda install --file r.nopysnptools.txt
    - conda install cython
    - pip install -r requirements.txt

  - name: macosx_py3
    os: osx
    osx_image: xcode11.2
    language: shell
    before_install:
    - brew install gcc@7
    - export CC=gcc-7
    - export CXX=g++-7
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install pip
    - fgrep -v pysnptools requirements.txt > r.nopysnptools.txt
    - conda install --file r.nopysnptools.txt
    - conda install cython
    - pip install --user -r requirements.txt

  - name: win_py3
    os: windows
    language: shell
    before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
    - Miniconda3-latest-Windows-x86_64.exe
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - conda install pip
    - fgrep -v pysnptools requirements.txt > r.nopysnptools.txt
    - conda install --file r.nopysnptools.txt
    - conda install cython
    - pip install -r requirements.txt

  - name: win_py2
    os: windows
    language: shell
    before_install:
    - choco install python2 --no-progress
    - choco install --ignore-dependencies vcpython27
    - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    - pip install -r requirements.txt
    - conda install cython
    - pip install wheel

install:
- python setup.py build_ext --inplace
- python setup.py sdist bdist_wheel

script:
- export PYTHONPATH=$TRAVIS_BUILD_DIR
- cd tests
- python test.py

deploy:
  provider: s3
  access_key_id: AKIAIJGTUJPG2US6OIOQ
  secret_access_key: $AWS_SECRET_KEY
  bucket: "traviscibucket"
  upload_dir: $TRAVIS_REPO_SLUG/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER.$TRAVIS_COMMIT/$TRAVIS_JOB_NAME
  local_dir: $TRAVIS_BUILD_DIR/dist
  skip_cleanup: true
  on:
    all_branches: true

#deploy:
#  provider: script
# #script: bash -c "ls -las dist"
#  script: bash -c "echo $NOT_NEEDED"
#  skip_cleanup: true
#  on:
#    branch: dev

notifications:
  email:
    recipients:
    - carlk@msn.com
    on_success: always
    on_failure: always
